"""empty message

Revision ID: fa7d869a7048
Revises: 17f005906c06
Create Date: 2026-06-07 01:55:09.293197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa7d869a7048'
down_revision: Union[str, Sequence[str], None] = '17f005906c06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('gold', 'silver', 'bronze', 'simple', name='statuschoices'), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('date_register', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('product_image',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('useres')
    op.add_column('product', sa.Column('subcategory_id', sa.Integer(), nullable=False))
    op.add_column('product', sa.Column('product_name', sa.String(length=30), nullable=False))
    op.add_column('product', sa.Column('price', sa.Integer(), nullable=False))
    op.add_column('product', sa.Column('article_number', sa.Integer(), nullable=False))
    op.add_column('product', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('product', sa.Column('product_type', sa.Boolean(), nullable=False))
    op.add_column('product', sa.Column('video', sa.String(), nullable=False))
    op.add_column('product', sa.Column('created_date', sa.Date(), nullable=False))
    op.create_unique_constraint(None, 'product', ['article_number'])
    op.create_foreign_key(None, 'product', 'subcategory', ['subcategory_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_constraint(None, 'product', type_='unique')
    op.drop_column('product', 'created_date')
    op.drop_column('product', 'video')
    op.drop_column('product', 'product_type')
    op.drop_column('product', 'description')
    op.drop_column('product', 'article_number')
    op.drop_column('product', 'price')
    op.drop_column('product', 'product_name')
    op.drop_column('product', 'subcategory_id')
    op.create_table('useres',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('avatar', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date_register', sa.DATE(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('useres_pkey')),
    sa.UniqueConstraint('email', name=op.f('useres_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('username', name=op.f('useres_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('review')
    op.drop_table('product_image')
    op.drop_table('users')
    # ### end Alembic commands ###
